import { create } from 'zustand'
import { persist } from 'zustand/middleware'

const T = {
  uz: {
    hero_title: 'IELTS Speaking',
    hero_title2: 'Ustasi bo\'ling',
    hero_sub: 'Band 6 dan Band 9 gacha — har bir savol uchun to\'liq tayyorgarlik materiallari',
    hero_badge: 'Part 2 & 3 · 4 Band darajasi · O\'zbek tarjimasi',
    available: 'Mavjud dossierlar',
    buy_btn: 'Telegramda sotib olish',
    contact_btn: 'Telegramga yozish',
    see_dossiers: 'Dossierlarni ko\'rish',
    price_label: 'Narxi',
    part23: 'Part 2 & 3',
    bands: 'Band 6 / 7 / 8 / 9',
    admin_btn: 'Admin kirish',
    footer: 'IELTSSHOKH — Speaking Mastery',
    footer_sub: 'Savol va to\'lov uchun:',
    no_dossiers: 'Hozircha dossierlar yo\'q. Tez kunda qo\'shiladi!',
    loading: 'Yuklanmoqda...',
    lang_uz: 'O\'zbek',
    lang_en: 'English',
    lang_ru: 'Русский',
    feat1_title: 'Xavfsiz kirish',
    feat1_sub: 'Har bir xaridor uchun alohida maxsus havola. Yuklab bo\'lmaydi.',
    feat2_title: 'Tez yetkazish',
    feat2_sub: 'To\'lov keyin darhol shaxsiy havola yuboriladi.',
    feat3_title: 'IELTS mutaxassisi',
    feat3_sub: 'Har bir javobda Band 6, 7, 8 va 9 darajalari ko\'rsatilgan.',
    how_title: 'Qanday sotib olish mumkin',
    step1: 'Qiziqtirgan dossier uchun Telegramga yozing',
    step2: 'To\'lovni amalga oshiring',
    step3: 'Shaxsiy havolani oling va dossierdan foydalaning',
  },
  en: {
    hero_title: 'Master IELTS',
    hero_title2: 'Speaking',
    hero_sub: 'From Band 6 to Band 9 — complete preparation materials for every question',
    hero_badge: 'Part 2 & 3 · 4 Band levels · Uzbek translation',
    available: 'Available Dossiers',
    buy_btn: 'Buy on Telegram',
    contact_btn: 'Message on Telegram',
    see_dossiers: 'View Dossiers',
    price_label: 'Price',
    part23: 'Part 2 & 3',
    bands: 'Band 6 / 7 / 8 / 9',
    admin_btn: 'Admin login',
    footer: 'IELTSSHOKH — Speaking Mastery',
    footer_sub: 'Questions & payment:',
    no_dossiers: 'No dossiers yet. Coming soon!',
    loading: 'Loading...',
    lang_uz: 'O\'zbek',
    lang_en: 'English',
    lang_ru: 'Русский',
    feat1_title: 'Secure Access',
    feat1_sub: 'Each buyer gets a unique private link. No downloads possible.',
    feat2_title: 'Instant Delivery',
    feat2_sub: 'Your personal link is sent immediately after payment.',
    feat3_title: 'IELTS Expert',
    feat3_sub: 'Every answer includes Band 6, 7, 8 and 9 sample responses.',
    how_title: 'How to buy',
    step1: 'Message us on Telegram about the dossier you want',
    step2: 'Complete the payment',
    step3: 'Receive your personal link and start studying',
  },
  ru: {
    hero_title: 'Мастерство IELTS',
    hero_title2: 'Speaking',
    hero_sub: 'С Band 6 до Band 9 — полные материалы подготовки к каждому вопросу',
    hero_badge: 'Part 2 & 3 · 4 уровня Band · Узбекский перевод',
    available: 'Доступные досье',
    buy_btn: 'Купить в Telegram',
    contact_btn: 'Написать в Telegram',
    see_dossiers: 'Смотреть досье',
    price_label: 'Цена',
    part23: 'Part 2 & 3',
    bands: 'Band 6 / 7 / 8 / 9',
    admin_btn: 'Вход для админа',
    footer: 'IELTSSHOKH — Speaking Mastery',
    footer_sub: 'Вопросы и оплата:',
    no_dossiers: 'Досье пока нет. Скоро будет!',
    loading: 'Загрузка...',
    lang_uz: 'O\'zbek',
    lang_en: 'English',
    lang_ru: 'Русский',
    feat1_title: 'Безопасный доступ',
    feat1_sub: 'Каждый покупатель получает уникальную ссылку. Скачивание невозможно.',
    feat2_title: 'Мгновенная доставка',
    feat2_sub: 'Личная ссылка отправляется сразу после оплаты.',
    feat3_title: 'Эксперт IELTS',
    feat3_sub: 'Каждый ответ включает образцы Band 6, 7, 8 и 9.',
    how_title: 'Как купить',
    step1: 'Напишите нам в Telegram о нужном досье',
    step2: 'Произведите оплату',
    step3: 'Получите личную ссылку и начните учиться',
  },
}

export const useLangStore = create(
  persist(
    (set, get) => ({
      lang: 'uz',
      setLang: (l) => set({ lang: l }),
      t: (key) => T[get().lang]?.[key] ?? key,
    }),
    { name: 'ielts-lang', partialize: s => ({ lang: s.lang }) }
  )
)
